version: '3.9'

services:
  db:
    image: postgres:15
    container_name: kafaat_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kafaat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: ahmedabdalla95/hr-core-server:latest
    container_name: kafaat_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/kafaat_db
    ports:
      - '4000:4000'

  frontend:
    image: ahmedabdalla95/hr-core-client:latest
    container_name: kafaat_frontend
    depends_on:
      - backend
    ports:
      - '3000:4004'

volumes:
  postgres_data:
