CREATE SCHEMA IF NOT EXISTS owner;

CREATE TABLE IF NOT EXISTS owner.tenants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  domain VARCHAR(255) UNIQUE NOT NULL,
  schema_name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);
CREATE SCHEMA IF NOT EXISTS template;

