name: Full CI

on:
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  quality-check:
    uses: ./.github/workflows/pr-quality-check.yml

  docker-build:
    needs: quality-check
    uses: ./.github/workflows/docker-build.yml
