name: PR Quality Checks

on:
  workflow_call:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      NX_DAEMON: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: ''

      - name: Configure npm to use cache
        run: npm config set cache ~/.npm --global

      - name: Install dependencies
        run: npm ci
      - name: Clear Nx Cache
        run: npx nx reset

      - name: Generate Project Graph
        run: npx nx graph --file=projects.json || true

      - name: Run Lint + Format
        run: |
          npm run format -- --verbose
          npm run lint:strict -- --verbose
        continue-on-error: true

      - name: Run Quality Checks
        run: npm run check:all
